name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: My first step -
          uses: actions/checkout@v4
        - name: JSON to variables
          uses: rgarcia-phi/json-to-variables@v1.1.0
          with:
            filename: "{a:b,c:d,e:f}"
            prefix: test
            masked: true
        - name: outputs
          run: |
              echo "${{ env.test_a }},${{ env.test_c }},${{ env.test_e }}"
                
